name: s3_api

services:
  s3-server:
    privileged: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - BUCKET_NAME
        - S3_BUCKET_DIR
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env
